/*------------------------------------------------------------------------------
<auto-generated>
     This code was generated from a template.

     Manual changes to this file may cause unexpected behavior in your application.
     Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/

using System.Web.Http;
using ODataV4 = Microsoft.AspNet.OData;
using Ez.Entities.Models;

namespace Ez.Web
{
    /// <summary></summary>
    public static class ODataRegistrations
    {
        /// <summary></summary>
        public static void Register(ODataV4.Builder.ODataModelBuilder builder4) {
        ;
        }
    }
}