using System.Data.Entity;
using Repository.Pattern.Ef6;
using Ez.Common;
/*------------------------------------------------------------------------------
<auto-generated>
    This code was generated from a template.

    Manual changes to this file may cause unexpected behavior in your application.
    Manual changes to this file will be overwritten if the code is regenerated.
</auto-generated>
------------------------------------------------------------------------------*/
namespace Ez.Entities.Models
{
    /// <summary></summary>
    public partial class EzEntities : DataContext
    {
    }
}